Set up API documentation page with hypothes.is embed
hbz/lobid-resources-web pull request #32
Opened 2017-01-30 13:23 UTC by fsteeg

Will resolve https://github.com/hbz/lobid-resources/issues/196

See http://lobid.org/resources/api

2017-01-30 13:53 UTC, acka47 commented
+1 As written in https://github.com/hbz/lobid-resources/issues/197, there will be at least one field hidden in the API response which, thus, shouldn't be documented. Accordingly, the documentation has to be updated as soon as the fields are hidden and/or other changes are made.

2017-01-30 14:25 UTC, ChristophEwertowski commented
+1

2017-01-31 08:03 UTC, fsteeg commented
> the documentation has to be updated as soon as the fields are hidden and/or other changes are made

The documents are actually fetched when the page is built, so it's always the current version.

2017-01-31 08:24 UTC, acka47 commented
> The documents are actually fetched when the page is built, so it's always the current version.

Very good.

2017-01-31 09:16 UTC, dr0i approved these changes

2017-01-31 09:17 UTC, dr0i requested changes

2017-01-31 09:17 UTC, dr0i commented on conf/messages.de
> +api.jsonld.info = JSON-API-Anfragen liefern JSON-LD (JSON for Linking Data). Um damit zu experimentieren können sie das JSON-LD oder URLs im <a href="{0}">JSON-LD Playground</a> einfügen.
"JSON for Linked Data"

2017-01-31 09:22 UTC, dr0i commented
I like the idea of using hypothesis :+1: 
A small thing:
couldn't find where the page header is set. What speaks against "der hbz-Verbundkatalog als Linked Open Data" instead of only "der hbz-Verbundkatalog als Open Data"?

2017-01-31 10:12 UTC, fsteeg commented on conf/messages.de
> +api.jsonld.info = JSON-API-Anfragen liefern JSON-LD (JSON for Linking Data). Um damit zu experimentieren können sie das JSON-LD oder URLs im <a href="{0}">JSON-LD Playground</a> einfügen.
Not what they call it: http://json-ld.org/

2017-01-31 10:16 UTC, fsteeg commented
> couldn't find where the page header is set. What speaks against "der hbz-Verbundkatalog als Linked Open Data" instead of only "der hbz-Verbundkatalog als Open Data"?

That is unrelated to this change. The header is included on every page via the main template and did not change in this pull request. My reason for the wording "der hbz-Verbundkatalog als Open Data im Web" was mainly that "Open" seemed redundant given the "im Web" part. If we want to discuss and change the wording, we should do so in a separate isse.

2017-01-31 11:17 UTC, dr0i commented
Re: LOD We can discuss this further on thursday.
+1 for the rest !

2017-01-31 11:18 UTC, dr0i approved these changes

2017-01-31 11:20 UTC, dr0i commented on conf/messages.de
> +api.jsonld.info = JSON-API-Anfragen liefern JSON-LD (JSON for Linking Data). Um damit zu experimentieren können sie das JSON-LD oder URLs im <a href="{0}">JSON-LD Playground</a> einfügen.
But here: https://en.wikipedia.org/wiki/Jsonld they reference https://www.w3.org/TR/json-ld-api/ which also name them "linked".
But it's not _so_ important for me.

2017-01-31 11:21 UTC, merged

2017-01-31 11:22 UTC, dr0i commented on conf/messages.de
> +api.jsonld.info = JSON-API-Anfragen liefern JSON-LD (JSON for Linking Data). Um damit zu experimentieren können sie das JSON-LD oder URLs im <a href="{0}">JSON-LD Playground</a> einfügen.
ah ... and it would be more in a tradition regarding "lobid.org" to call it Linked Open Data , not "linking data".

2017-02-02 09:32 UTC, fsteeg commented
Result of our discussion:

1) We will replace "Open Data on the Web" with "Linked Open Data" in the header
2) We will link to http://json-ld.org/ from the API doc page and remove the "(JSON for Linking Data)"